from __future__ import annotations

from datetime import datetime, timedelta, timezone

from ..schemas import (
    CertificateInfo,
    EvidenceStatus,
    ProtocolName,
    SessionAnalysis,
    SessionFeatures,
    StartTLSInfo,
    TLSInfo,
)


def demo_sessions() -> list[SessionAnalysis]:
    now = datetime.now(timezone.utc)
    valid_until = now + timedelta(days=280)
    expired_until = now - timedelta(days=10)

    secure = SessionAnalysis(
        session_id="demo-smtp-secure",
        tcp_stream_id="7",
        client_ip="10.0.0.10",
        client_port=51000,
        server_ip="10.0.0.20",
        server_port=587,
        protocol=ProtocolName.SMTP,
        protocol_confidence=0.99,
        first_frame=1,
        last_frame=42,
        start_time=now,
        end_time=now + timedelta(seconds=2),
        duration_ms=2000,
        packet_count=42,
        byte_count=18500,
        stream_status=EvidenceStatus.COMPLETE,
        starttls=StartTLSInfo(
            advertised=True,
            command_seen=True,
            accepted=True,
            upgrade_successful=True,
            implicit_tls=False,
            evidence=["EHLO advertised STARTTLS", "STARTTLS accepted", "TLS handshake followed"],
        ),
        tls=TLSInfo(
            detected=True,
            handshake_status=EvidenceStatus.COMPLETE,
            client_hello_seen=True,
            server_hello_seen=True,
            certificate_seen=True,
            tls_version="TLS 1.3",
            version_source="SERVER_HELLO",
            offered_versions=["TLS 1.2", "TLS 1.3"],
            cipher_suite="TLS_AES_256_GCM_SHA384 (0x1302)",
            cipher_source="SERVER_HELLO",
            offered_cipher_suites=["TLS_AES_256_GCM_SHA384 (0x1302)", "TLS_AES_128_GCM_SHA256 (0x1301)"],
            key_exchange="X25519",
            forward_secrecy=True,
            named_group="x25519",
            signature_algorithm="rsa_pss_rsae_sha256",
            sni="mail.example.test",
        ),
        certificate=CertificateInfo(
            present=True,
            subject="CN=mail.example.test",
            issuer="CN=Demo Enterprise CA",
            common_name="mail.example.test",
            subject_alternative_names=["mail.example.test"],
            valid_from=now - timedelta(days=80),
            valid_until=valid_until,
            days_remaining=280,
            expired=False,
            not_yet_valid=False,
            self_signed=False,
            hostname_match=True,
            public_key_algorithm="RSA",
            public_key_bits=2048,
            signature_algorithm="sha256WithRSAEncryption",
            signature_hash_algorithm="sha256",
            chain_status="COMPLETE",
            chain_length=2,
            chain_complete=True,
        ),
        features=SessionFeatures(
            protocol="SMTP",
            server_port=587,
            packet_count=42,
            byte_count=18500,
            duration_ms=2000,
            retransmission_rate=0,
            tls_detected=1,
            tls_version_rank=5,
            cipher_strength_score=95,
            key_exchange_code=3,
            forward_secrecy=1,
            starttls_advertised=1,
            starttls_success=1,
            certificate_present=1,
            certificate_key_bits=2048,
            certificate_signature_strength=3,
            hostname_match=1,
            chain_complete=1,
            sni_present=1,
            handshake_complete=1,
        ),
        evidence_completeness=1.0,
    )

    weak = SessionAnalysis(
        session_id="demo-imap-weak",
        tcp_stream_id="12",
        client_ip="10.0.0.11",
        client_port=52000,
        server_ip="10.0.0.21",
        server_port=143,
        protocol=ProtocolName.IMAP,
        protocol_confidence=0.99,
        first_frame=100,
        last_frame=154,
        start_time=now,
        end_time=now + timedelta(seconds=8),
        duration_ms=8000,
        packet_count=55,
        byte_count=31000,
        retransmission_count=3,
        stream_status=EvidenceStatus.COMPLETE,
        starttls=StartTLSInfo(
            advertised=True,
            command_seen=True,
            accepted=True,
            upgrade_successful=True,
            plaintext_authentication_seen=False,
            evidence=["IMAP STARTTLS accepted"],
        ),
        tls=TLSInfo(
            detected=True,
            handshake_status=EvidenceStatus.COMPLETE,
            client_hello_seen=True,
            server_hello_seen=True,
            certificate_seen=True,
            tls_version="TLS 1.0",
            version_source="SERVER_HELLO",
            offered_versions=["TLS 1.0", "TLS 1.1", "TLS 1.2"],
            cipher_suite="TLS_RSA_WITH_3DES_EDE_CBC_SHA (0x000a)",
            cipher_source="SERVER_HELLO",
            key_exchange="RSA",
            forward_secrecy=False,
            sni="old-mail.example.test",
            handshake_failures=1,
            repeated_client_hellos=2,
        ),
        certificate=CertificateInfo(
            present=True,
            subject="CN=old-mail.example.test",
            issuer="CN=old-mail.example.test",
            common_name="old-mail.example.test",
            valid_from=now - timedelta(days=800),
            valid_until=expired_until,
            days_remaining=-10,
            expired=True,
            not_yet_valid=False,
            self_signed=True,
            hostname_match=False,
            public_key_algorithm="RSA",
            public_key_bits=1024,
            signature_algorithm="sha1WithRSAEncryption",
            signature_hash_algorithm="sha1",
            weak_signature=True,
            chain_status="INCOMPLETE",
            chain_length=1,
            chain_complete=False,
        ),
        features=SessionFeatures(
            protocol="IMAP",
            server_port=143,
            packet_count=55,
            byte_count=31000,
            duration_ms=8000,
            retransmission_rate=0.0545,
            handshake_failure_count=1,
            tls_detected=1,
            tls_version_rank=2,
            cipher_strength_score=20,
            key_exchange_code=1,
            forward_secrecy=0,
            starttls_advertised=1,
            starttls_success=1,
            certificate_present=1,
            certificate_expired=1,
            certificate_self_signed=1,
            certificate_key_bits=1024,
            certificate_signature_strength=1,
            hostname_match=0,
            chain_complete=0,
            sni_present=1,
            handshake_complete=1,
            repeated_client_hellos=2,
        ),
        evidence_completeness=1.0,
    )

    plaintext = SessionAnalysis(
        session_id="demo-pop3-plaintext",
        tcp_stream_id="19",
        client_ip="10.0.0.12",
        client_port=53000,
        server_ip="10.0.0.22",
        server_port=110,
        protocol=ProtocolName.POP3,
        protocol_confidence=0.96,
        first_frame=200,
        last_frame=219,
        start_time=now,
        end_time=now + timedelta(seconds=1),
        duration_ms=1000,
        packet_count=20,
        byte_count=7200,
        stream_status=EvidenceStatus.COMPLETE,
        starttls=StartTLSInfo(
            advertised=False,
            command_seen=False,
            accepted=False,
            upgrade_successful=False,
            plaintext_authentication_seen=True,
            evidence=["POP3 USER/PASS observed before encryption"],
        ),
        tls=TLSInfo(detected=False, handshake_status=EvidenceStatus.UNKNOWN),
        features=SessionFeatures(
            protocol="POP3",
            server_port=110,
            packet_count=20,
            byte_count=7200,
            duration_ms=1000,
            tls_detected=0,
            tls_version_rank=0,
            cipher_strength_score=0,
            key_exchange_code=0,
            forward_secrecy=-1,
            starttls_advertised=0,
            starttls_success=0,
            plaintext_authentication=1,
            certificate_present=0,
            hostname_match=-1,
            chain_complete=-1,
            handshake_complete=0,
        ),
        evidence_completeness=0.95,
    )
    return [secure, weak, plaintext]
